version: '3'

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: 
      context: backend
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 rideshare_app.asgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env

volumes:
  postgres_data:
