version: '3'

services:
  db:
    container_name: rideshare-db
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: rideshare-redis
    image: redis
    ports:
      - "6379:6379"

  backend:
    container_name: rideshare-backend
    image: alexjr2002/rideshare-backend
    # build: 
    #   context: backend
    #   dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env
  
  frontend:
    container_name: rideshare-frontend
    image: alexjr2002/rideshare-frontend
    # build:
    #   context: frontend
    #   dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "80:4200"
    depends_on:
      - backend

volumes:
  postgres_data:
